spring:
 application:
  name: shopping-cart-service

 profiles:
  active: localhost

server:
 port: 5862
 
---
spring:
 config:
  activate:
   on-profile: localhost
 cloud:
  config: 
   uri: http://localhost:5859
  

eureka:
 instance:
  hostname: localhost
  instance-id: ${spring.application.name}
 client:
  service-url:
   default-zone: http://localhost:8761/eureka/
   
---
spring:
 datasource: 
  url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
  username: postgres
  password: 12345
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties: 
   hibernate:
    format-sql: true
  
