eureka:
  instance:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      uri: http://localhost:5859