eureka:
  instance:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      
spring:
  datasource :
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
    properties:
      hibernate :
        format_sql: true
        
    